/*
 * Copyright 2015 LinkedIn Corp.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.linkedin.gradle.validator.hadoop

import org.gradle.api.GradleException

/**
 * The HadoopValidatorUtil class provides some static helper methods which may be used throughout
 * the Plugin by any of the validators.
 */
class HadoopValidatorUtil {
  /**
   * This function scans the passed properties object and returns the NameNode address and port.
   *
   * @param properties The properties object generated by reading .hadoopValidatorProperties
   * @param projectDir The project home directory
   * @return The qualified name node address with port
   */
  static String getNameNodeAddress(Properties properties, String projectDir) {
    String clusterURIString
    if (properties != null && properties.containsKey("NameNode")) {
      clusterURIString = properties.getProperty("NameNode")
    } else {
      throw new GradleException("Please specify NameNode address in $projectDir/.hadoopValidatorProperties")
    }

    if (!(clusterURIString ==~ /hdfs\:\/\/.*?\:[0-9]+/)) {
      throw new GradleException("Invalid NameNode specification in $projectDir/.hadoopValidatorProperties\n" +
          "Please specify NameNode address as NameNode=hdfs://<namenode>:<port>")
    }
    return clusterURIString
  }

  /**
   * This function scans the passed properties object and returns the Ivy repository URL.
   *
   * @param properties The properties object generated by reading .hadoopValidatorProperties
   * @param projectDir The project home directory
   * @return The Ivy repository URL
   */
  static String getRepoURL(properties, String projectDir) {
    if (properties.containsKey("repositoryURL")) {
      return properties.getProperty("repositoryURL")
    }
    throw new GradleException("Please specify the Ivy repository URL in $projectDir/.hadoopValidatorProperties")
  }
}
